[package]
name = "rustkatas"
version = "0.1.0"
authors = ["Pedro Moreira Santos @pedromsantos"]
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-case = "3.1.0"