[package]
name = "rustkatas"
version = "0.1.0"
authors = ["Pedro Moreira Santos @pedromsantos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-case = "0.3.3"