[package]
name = "rustkatas"
version = "0.1.0"
authors = ["Pedro Moreira Santos @pedromsantos"]
edition = "2021"

[dev-dependencies]
test-case = { version = "3.1.0" }
pretty_assertions = { version = "1.0.0" }
proptest = "1.3.1"
